apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-data-pvc-3
  namespace: plexserver
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: plexserver-data-pv-3