apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-data-pvc
  namespace: plexserver
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 100Gi