apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-data-pv
  namespace: plexserver
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.2
    path: "/volume1/filme3/"
  mountOptions:
    - nfsvers=4.2