apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-data-pv-1
  namespace: plexserver
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.2
    path: "/volume2/filme_1/"
  mountOptions:
    - nfsvers=4.0