apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-data-pv
  namespace: plexserver
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.144
    path: "/mnt/usb/volume/1/share/kubernetes/plex/data/"
  mountOptions:
    - nfsvers=4.2