apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-data-pvc
  namespace: plexserver
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: plexserver-data-pv