apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-config-pv
  namespace: plexserver
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.144
    path: "/mnt/usb/volume/1/share/kubernetes/plex/config/"
  mountOptions:
    - nfsvers=4.2